/**
 * Metadata for the application
 */

export interface IApplication {
  /**
   * Handle to the application, automatically generated by xiaobai.
   */
  handle: string;
  /**
   * Name of the application
   */
  name: string;
  /**
   * Size and position of the application window
   */
  boundary: {
    /** 
     * Distance to the left of the application window,
     * between 0 and 1.
     */
    x: number;
    /** 
     * Distance from the top of the window, 
     * between 0 and 1.
     */
    y: number;
    /**
     * Width of application
     */
    width: number;
    /**
     * Height of application
     */
    height: number;
  }
}
